### ISSUE TITLE
Dear Johnseni

### ISSUE THREAD

**Issue by codomposer** [johnoseni1/My-Portfolio-V1#2]
I saw your portfolio and it is awesome
Can I ask some question?
![image](https://user-images.githubusercontent.com/101377478/173194474-0ef5f719-a855-4d10-874f-9aec6086cfce.png)
could you tell me how to get these honor?

**Comment by johnoseni1** [comment]
I think it is most os what i have contributed to, that is why i got those, you can check more online for that, 

I will be closing this issue for now

**Comment by codomposer** [comment]
Sorry to bother you
can i take part in your team?
